name: Automation APIs

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment (ex: qa, staging, dev)'
        required: true
        default: 'qa'

jobs:
  pre-conditions:
    runs-on: ubuntu-latest
    env:
      ENV: ${{ github.event.inputs.env || 'qa' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

  test:
    runs-on: ubuntu-latest
    needs: pre-conditions  
    env:
      ENV: ${{ github.event.inputs.env || 'qa' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Run Tests
        run: |
          echo "Executing tests on: $ENV"
          ./gradlew clean test -Denv=$ENV

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: app/build/allure-results

  deploy:
    runs-on: ubuntu-latest
    needs: test 
    permissions:
      contents: write
    steps:
      - name: Checkout gh-pages Branch (for Allure History)
        if: always()
        uses: actions/checkout@v4
        with:
          ref: gh-pages           
          path: allure-history       

      - name: Download Allure Results Artifact
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: app/build/allure-results

      - name: Build Allure Report with History
        if: always()
        uses: simple-elf/allure-report-action@v1.7
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: app/build/allure-results

      - name: Publish Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
