name: Deploy Allure Report to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to run tests (ex: qa, staging, dev)'
        required: true
        default: 'qa'
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests with Gradle
        run: ./gradlew clean test -Denv=${{ github.event.inputs.env }}

      - name: Generate Allure Report
        run: ./gradlew allureReport

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/allure-report
